# Generated by Django 4.2.6 on 2023-10-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField()),
                ('person_id', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('type', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('duration', models.IntegerField()),
                ('is_high_level', models.BooleanField()),
                ('plausability', models.BooleanField()),
                ('provider', models.CharField(max_length=255)),
            ],
        ),
    ]
