# Generated by Django 4.2.6 on 2024-04-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('sensor_id', models.IntegerField()),
                ('sensor_status', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'motions',
            },
        ),
        migrations.AlterModelOptions(
            name='plugs',
            options={'verbose_name_plural': 'plugs'},
        ),
    ]
